# Molecule create playbook for execution-environment scenario.
#
# Builds the collection artifact and the Execution Environment image.

---

- name: "Molecule | Create (EE) | Build Execution Environment"
  hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars:
    __testing_ee_image_name: "molecule-ee-postfix-test"
    __testing_ee_image_tag: "latest"
    __testing_collection_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | ansible.builtin.dirname | ansible.builtin.dirname }}"
    __testing_build_dir: "{{ molecule_ephemeral_directory }}/ee-build"
    podman_executable: "{{ lookup('env', 'MOLECULE_PODMAN_EXECUTABLE') | default('podman', true) }}"

  tasks:

    - name: "Molecule | Create (EE) | Check for required tools"
      ansible.builtin.command:
        cmd: "{{ item }} --version"
      loop:
        - "ansible-builder"
        - "{{ podman_executable }}"
      changed_when: false


    - name: "Molecule | Create (EE) | Create build directory"
      ansible.builtin.file:
        path: "{{ __testing_build_dir }}"
        state: "directory"
        mode: "u=rwx,g=rx,o=rx"


    - name: "Molecule | Create (EE) | Build collection artifact"
      ansible.builtin.command:
        cmd: "ansible-galaxy collection build --force --output-path {{ __testing_build_dir }}"
        chdir: "{{ __testing_collection_root }}"
      changed_when: true


    - name: "Molecule | Create (EE) | Find collection artifact"
      ansible.builtin.find:
        paths: "{{ __testing_build_dir }}"
        patterns: "foundata-postfix-*.tar.gz"
      register: __testing_collection_artifact


    - name: "Molecule | Create (EE) | Fail if no artifact found"
      ansible.builtin.fail:
        msg: "No collection artifact found in {{ __testing_build_dir }}"
      when: __testing_collection_artifact['files'] | length == 0


    - name: "Molecule | Create (EE) | Create execution-environment.yml for build"
      ansible.builtin.copy:
        dest: "{{ __testing_build_dir }}/execution-environment.yml"
        mode: "u=rw,g=r,o=r"
        content: |
          ---
          version: 3

          images:
            base_image:
              name: "quay.io/ansible/ansible-runner:latest"

          dependencies:
            galaxy:
              collections:
                - name: "{{ __testing_collection_artifact['files'][0]['path'] }}"
                  type: "file"


    - name: "Molecule | Create (EE) | Build Execution Environment image"
      ansible.builtin.command:
        cmd: >-
          ansible-builder build
          --tag {{ __testing_ee_image_name }}:{{ __testing_ee_image_tag }}
          --container-runtime {{ podman_executable }}
          --file execution-environment.yml
          --verbosity 2
        chdir: "{{ __testing_build_dir }}"
      changed_when: true


    - name: "Molecule | Create (EE) | Store EE image name for later stages"
      ansible.builtin.copy:
        dest: "{{ molecule_ephemeral_directory }}/ee-image-name.txt"
        content: "{{ __testing_ee_image_name }}:{{ __testing_ee_image_tag }}"
        mode: "u=rw,g=r,o=r"
