# Molecule destroy playbook for execution-environment scenario.
#
# Cleans up the built Execution Environment image.

---

- name: "Molecule | Destroy (EE) | Clean up Execution Environment"
  hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars:
    podman_executable: "{{ lookup('env', 'MOLECULE_PODMAN_EXECUTABLE') | default('podman', true) }}"

  tasks:

    - name: "Molecule | Destroy (EE) | Check if EE image name file exists"
      ansible.builtin.stat:
        path: "{{ molecule_ephemeral_directory }}/ee-image-name.txt"
      register: __testing_ee_image_name_file


    - name: "Molecule | Destroy (EE) | Read EE image name"
      ansible.builtin.slurp:
        src: "{{ molecule_ephemeral_directory }}/ee-image-name.txt"
      register: __testing_ee_image_name_raw
      when: __testing_ee_image_name_file['stat']['exists']


    - name: "Molecule | Destroy (EE) | Set EE image name fact"
      ansible.builtin.set_fact:
        __testing_ee_image_name: "{{ __testing_ee_image_name_raw['content'] | ansible.builtin.b64decode | ansible.builtin.trim }}"
      when: __testing_ee_image_name_file['stat']['exists']


    - name: "Molecule | Destroy (EE) | Remove EE image"
      ansible.builtin.command:
        cmd: "{{ podman_executable }} rmi --force {{ __testing_ee_image_name }}"
      when:
        - __testing_ee_image_name is defined
        - __testing_ee_image_name | ansible.builtin.length > 0
      changed_when: true
      failed_when: false


    - name: "Molecule | Destroy (EE) | Prune dangling images from build"
      ansible.builtin.command:
        cmd: "{{ podman_executable }} image prune --force"
      changed_when: true
      failed_when: false
