# Tasks for the Molecule converge stage: Execute the collection role "run"
# against all driver-created instances.


# This prevents testing whether the role itself verifies these facts'
# availability but it avoids fragile workarounds (like parsing container
# names) if additional platform specific preparations are needed.
# No problem as our roles using the subset do proper availability checks.
- name: "Molecule | Converge | Gather playbook-specific facts"
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
  when:
    - ansible_facts['distribution'] is not defined or
      ansible_facts['os_family'] is not defined


- name: "Molecule | Converge | Include the foundata.postfix.run role"
  ansible.builtin.include_role:
    name: "foundata.postfix.run"
  vars:
    run_postfix_state: "present"
    run_postfix_maincf_settings:
      myhostname: "smtp.example.com"
      mydomain: "example.com"
      inet_interfaces: "all"
      inet_protocols: "all"
      smtp_tls_security_level: "may"
      smtpd_tls_security_level: "may"
      smtp_tls_note_starttls_offer: "yes"
      smtpd_tls_cert_file: "{{ '/etc/pki/tls/certs' if (ansible_facts['os_family'] | lower) == 'redhat' else '/etc/ssl/certs' }}/dummy-cert.pem"
      smtpd_tls_key_file: "{{ '/etc/pki/tls/certs' if (ansible_facts['os_family'] | lower) == 'redhat' else '/etc/ssl/certs' }}/dummy-cert.pem"
      smtpd_tls_dh1024_param_file: "{{ '/etc/pki/tls/certs' if (ansible_facts['os_family'] | lower) == 'redhat' else '/etc/ssl/certs' }}/dhparam_ffdhe2048" # see https://www.postfix.org/postconf.5.html#smtpd_tls_dh1024_param_file
      message_size_limit: 52428800 # 50 MiB; max size of a incoming email
      mailbox_size_limit: 0 # 0 == unlimited; max mailbox size should be controlled by the mailserver
      relayhost: "[relay.example.org]:25"
      header_size_limit: 4096000
      virtual_alias_maps: "btree:/etc/postfix/this_value_should_get_overwritten" # setting "run_postfix_handle_relay_domains: true" should overwrite this
    run_postfix_mastercf_settings:
      smtp:
        type: "inet"
        private: "n"
        unpriv: "-"
        chroot: "n"
        wakeup: "-"
        maxproc: "-"
        command_args: "smtpd"
      submission:
        type: "inet"
        private: "n"
        unpriv: "-"
        chroot: "n"
        wakeup: "-"
        maxproc: "-"
        command_args: "smtpd"
      2525: # Test if a unusual port works
        type: "inet"
        private: "n"
        unpriv: "-"
        chroot: "n"
        wakeup: "-"
        maxproc: "-"
        command_args: "smtpd"
    run_postfix_handle_relay_domains: true
    run_postfix_relay_domains:
      - "example.com"
      - "example.net"
      - "example.org"
      - "foo.example.org"
    run_postfix_handle_transport_maps: true
    run_postfix_transport_maps:
      "example.com": "lmtp:unix:/var/spool/postfix/private/lmtp-dovecot"
      "example.net": "lmtp:127.0.0.1:24"
      "example.org": "[192.168.0.1]"
      "foo.example.org": "[mailrelay.foo.example.org]:123"
    run_postfix_handle_virtual: true
    run_postfix_virtual_alias_domains:
      - "example.com"
      - "example.net"
    run_postfix_virtual_alias_maps:
      "admin@example.com":
        - "admin@actual-destination.example.com"
      "distribution@example.com":
        - "user1@actual-destination.example.com"
        - "user2@actual-destination.example.com"
        - "user3@actual-destination.example.com"
        - "user3@actual-destination.example.com"
      "@example.com": # catch-all for example.com
        - "office@example.com"
      "@example.net": # catch-all for example.net, rewrite all @example.net addresses to @example.com
        - "example.com"
    run_postfix_handle_canonical: true
    run_postfix_canonical_recipient:
      "old.name@example.com": "new.name@example.com"
      "@example.com": "@example.net"
    run_postfix_canonical_sender:
      "/.+/": "do-not-reply@example.com" # rewrite all outgoing mail addresses
    run_postfix_handle_relocated_maps: true
    run_postfix_relocated_maps:
      "user124@example.com": "user123@example.net"
      "user345@example.com": "user345 has left, please contact him at ACME now."
