# Role argument validation.
#
# See defaults/main.yml for details on each variable. For more information on
# the argument_specs.yml format, refer to the official Ansible documentation:
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation

---

argument_specs:

  # foundata.postfix/roles/run/tasks/main.yml entry point
  main:
    short_description: "Main entry point for the foundata.postfix.run role"
    options:

      run_postfix_state:
        type: "str"
        required: true
        choices:
          - "present"
          - "absent"

      run_postfix_autoupgrade:
        type: "bool"
        required: true

      run_postfix_service_state:
        type: "str"
        required: true
        choices:
          - "enabled"
          - "disabled"
          - "running"
          - "unmanaged"

      run_postfix_maincf_settings:
        type: "dict"
        required: true

      run_postfix_mastercf_settings:
        type: "dict"
        required: true

      run_postfix_handle_relay_domains:
        type: "bool"
        required: true

      run_postfix_relay_domains:
        type: "list"
        elements: "str"
        required: true

      run_postfix_handle_transport_maps:
        type: "bool"
        required: true

      run_postfix_transport_maps:
        type: "dict"
        required: true

      run_postfix_handle_virtual:
        type: "bool"
        required: true

      run_postfix_virtual_alias_domains:
        type: "list"
        elements: "str"
        required: true

      run_postfix_virtual_alias_maps:
        type: "dict"
        required: true

      run_postfix_handle_canonical:
        type: "bool"
        required: true

      run_postfix_canonical_recipient:
        type: "dict"
        required: true

      run_postfix_canonical_sender:
        type: "dict"
        required: true
