# Role argument validation.
#
# See defaults/main.yml for details on each variable. For more information on
# the argument_specs.yml format, refer to the official Ansible documentation:
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation

---

argument_specs:

  # foundata.postfix/roles/run/tasks/main.yml entry point
  main:
    short_description: "Main entry point for the foundata.postfix.run role"
    options:

      run_postfix_state:
        type: "str"
        required: true
        choices:
          - "present"
          - "absent"

      run_postfix_autoupgrade:
        type: "bool"
        required: true

      run_postfix_service_state:
        type: "str"
        required: true
        choices:
          - "enabled"
          - "disabled"
          - "running"
          - "unmanaged"

      run_postfix_maincf_settings:
        type: "dict"
        required: true

      run_postfix_mastercf_settings:
        type: "dict"
        required: true

      run_postfix_relay_domains_manage:
        type: "bool"
        required: true

      run_postfix_relay_domains_list:
        type: "list"
        elements: "str"
        required: true

      run_postfix_canonical_manage:
        type: "bool"
        required: true

      run_postfix_canonical_recipient_map:
        type: "dict"
        required: true

      run_postfix_canonical_sender_map:
        type: "dict"
        required: true

      run_postfix_generic_manage:
        type: "bool"
        required: true

      run_postfix_generic_map:
        type: "dict"
        required: true

      run_postfix_relocated_manage:
        type: "bool"
        required: true

      run_postfix_relocated_map:
        type: "dict"
        required: true

      run_postfix_transport_manage:
        type: "bool"
        required: true

      run_postfix_transport_map:
        type: "dict"
        required: true

      run_postfix_virtual_manage:
        type: "bool"
        required: true

      run_postfix_virtual_aliasdomains_list:
        type: "list"
        elements: "str"
        required: true

      run_postfix_virtual_alias_map:
        type: "dict"
        required: true

      run_postfix_smtp_sasl_password_manage:
        type: "bool"
        required: true

      run_postfix_smtp_sasl_password_map:
        type: "dict"
        required: true
