# Include where useful: SMTP dialog (STARTTLS)

- name: "Molecule | Verify | SMTP (STARTTLS, OpenSSL) {{ __testing_hostdata['host'] ~ ':' ~ __testing_hostdata['port'] }}"
  ansible.builtin.expect:
    command: >
        /usr/bin/openssl
          s_client -starttls smtp -crlf -quiet
          -connect {{ __testing_hostdata['host'] ~ ':' ~ __testing_hostdata['port']  | ansible.builtin.quote }}
    responses:
      # Wait for response
      '(?i)250.*\r?\n': "QUIT"
      # Wait for response to QUIT
      '(?i)221.*\r?\n': ""
    timeout: 5
  changed_when: false
  register: __testing_run_postfix_smtp_starttlsopenssl_result


- name: "Molecule | Verify | Assert correct answers: SMTP (STARTTLS, OpenSSL) {{ __testing_hostdata['host'] ~ ':' ~ __testing_hostdata['port'] }}"
  ansible.builtin.assert:
    that:
      - __testing_run_postfix_smtp_starttlsopenssl_result is succeeded
      - ('verify return:') in __testing_run_postfix_smtp_starttlsopenssl_result['stdout']
      - ('250 ') in __testing_run_postfix_smtp_starttlsopenssl_result['stdout']
      - ('221 2.0.0 Bye') in __testing_run_postfix_smtp_starttlsopenssl_result['stdout']
    fail_msg: "SMTP STARTTLS check failed: Expected proper responses to SMTP commands"
