# Default variables and values for this role.
#
# These variables are designed to be easily overridden (as they have a low
# precedence) and typically allow users to customize the role's behavior.
# Each variable should have a clear comment above it, describing its purpose
# and how it fits into the role's functionality.

---

# String. Determines whether the managed resources should be "present" or
# "absent". Defaults to "present". Possible values:
#
# - "present": Ensures that required components, such as software packages,
#   are installed and configured.
# - "absent": Reverts changes as much as possible, such as removing packages,
#   deleting created users, stopping services, restoring modified settings, …
run_postfix_state: "present"


# Boolean. If set to true, all managed packages will be upgraded during each
# Ansible run (e.g., when the package provider detects a newer version than
# the currently installed one). Defaults to false.
run_postfix_autoupgrade: false


# String. Defines the status of the service(s). Defaults to "enabled".
# Possible values:
#
# - "enabled": Service is running and will start automatically at boot.
# - "disabled": Service is stopped and will not start automatically at boot.
# - "running": Service is running but will not start automatically at boot.
#   This can be used to start a service on the first Ansible run without
#   enabling it for boot.
# - "unmanaged": Service will not start at boot, and Ansible will not
#   manage its running state. This is primarily useful when services are
#   monitored and managed by systems other than Ansible.
#
# The singular form ("service") is used for simplicity. However, the defined
# status applies to all services if multiple are being managed by this role.
run_postfix_service_state: "enabled"


# Additional configuration for Postfix daemon (additional config values or to
# overwrite defaults).
#
# Use standard Postfix option names as keys with their corresponding values.
#
# Dictionary structure:
#
# - Keys: Standard Postfix option names (as defined in postconf documentation)
# - Values: Corresponding configuration values.Common options include:
#   myhostname: FQDN of the mail system
#   mydomain: Domain part of the FQDN
#   myorigin: Domain to append to locally posted mail
#   inet_interfaces: Network interfaces to listen on
#   inet_protocols: IP protocols to use (ipv4, ipv6, all)
#   mynetworks: Trusted SMTP clients for relay
#
# Reference commands:
# - postconf: print all current active values
# - postconf -n: print all active, explicitly set options
# - postconf -d: print all options with their default
#
# Please note that you do not need own handler for postmap when using
# "hash|btree|dbm:" somewhere. The role's handler is intelligent enough to scan
# the config for hash|btree|dbm:/path values. Just notify "run_postfix: update
# lookup tables" on changes when writing additional, own tasks.
#
# For a complete list of options, see https://www.postfix.org/postconf.5.html
run_postfix_maincf_settings:
  {} # see __run_postfix_maincf_settings_defaults in vars/main.yml for the defaults


# Additional configuration for Postfix master process (master.cf). For details
# on the syntax of the fields/values, see the master(5) manual page (command:
# "man 5 master" or online: http://www.postfix.org/master.5.html).
#
# Dictionary structure:
#
# - Keys: service names (e.g., smtp, submission, 127.0.0.1:smtp, 12345)
# - Values: configuration parameters for that service
#
# Example:
#
#   smtp: # Service for standard SMTP (Port 25)
#     type: "inet" # Network socket type
#     private: "n" # Private service
#     unpriv: "-" # Unprivileged service
#     chroot: "n" # Run in chroot, usually n for Postfix > v3.0.0
#     wakeup: "-" # Wakeup time
#     maxproc: "-" # Max processes
#     command_args: "smtpd" # Command and arguments
#   submission: # Service for submission (Port 587)
#     type: "inet"
#     private: "n"
#     unpriv: "-"
#     chroot: "n"
#     wakeup: "-"
#     maxproc: "-"
#     command_args: "smtpd"
run_postfix_mastercf_settings:
  {} # see __run_postfix_mastercf_settings_defaults in vars/main.yml for the defaults


# Switch to control if relay domains settings are handled by this role.
#
# When set to true (which is the default), the role will:
#
# 1. Create and manage a config file for relay domains using the
#    run_postfix_relay_domains variable for the contents
# 2. Set (or override) main.cf settings for the relay_domains option
#    accordingly.
#
# When false, you'll need to configure these settings manually through
# run_postfix_maincf_settings or through other means.
run_postfix_handle_relay_domains: true


# Relay domains for Postfix. This list of relay domains for which Postfix will
# accept mail for relaying to their final destinations.
#
# Example:
#   - "example.com"
#   - "example.net"
#   - "example.org"
#   - "foo.example.org"
#
# Will be ignored if run_postfix_handle_relay_domains is set to false.
run_postfix_relay_domains:
  [] # see __run_postfix_relay_domains_defaults in vars/main.yml for the defaults


# Switch to control if transport mappings settings are handled by this role.
#
# When set to true (which is the default), the role will:
#
# 1. Create and manage a config file for relay domains using the
#    run_postfix_transport_maps variable for the contents
# 2. Set (or override) main.cf settings for the transport_maps option
#    accordingly.
#
# When false, you'll need to configure these settings manually through
# run_postfix_maincf_settings or through other means.
run_postfix_handle_transport_maps: true


# Domain transport mapping for Postfix. This defines where to send emails to
# for the listed domains in a structured format.
#
# Attention: Do not forget to use square brackets to force DNS A record instead
#            of MX record lookups
#
# Dictionary structure:
#
# - Keys: criterions / pattern, usually an email address
# - Values: Lists of destinations, usually email addresses
#
# Example:
#
#   "example.com": "lmtp:unix:/var/spool/postfix/private/lmtp-dovecot"
#   "example.net": "lmtp:127.0.0.1:24"
#   "example.org": "[192.168.0.1]"
#   "foo.example.org": "[mailrelay.foo.example.org:123"
#   # dedicated relay for Microsoft
#   "/.*@(outlook|hotmail|live|msn)\..*/i": "[relay.example.com]:587"
#
# will be ignored if run_postfix_handle_transport_maps is set to false.
run_postfix_transport_maps:
  {} # see __run_postfix_transport_maps_defaults in vars/main.yml for the defaults


# Switch to control if virtual alias domains and mappings are handled by this
# role.
#
# When set to true (which is the default), the role will:
#
# 1. Create and manage a config file for virtual domains using the
#    run_postfix_virtual_alias_domains variable for the contents
# 2. Create and manage a config file for virtual mappings using the
#    run_postfix_virtual_alias_maps variable for the contents
# 3. Set (or override) main.cf settings for the virtual_alias_domains and
#    virtual_alias_maps options accordingly
#
# When false, you'll need to configure these settings manually through
# run_postfix_maincf_settings or through other means.
run_postfix_handle_virtual: true


# Virtual aliases domains for Postfix. This tells Postfix to accept incoming
# emails for a list of virtual domains. Mappings for them are defined via
# run_postfix_virtual_alias_maps
#
# Example:
#   - "example.com"
#   - "example.net"
#
# will be ignored if run_postfix_handle_virtual is set to false.
run_postfix_virtual_alias_domains:
  [] # see __run_postfix_virtual_alias_domains_defaults in vars/main.yml for the defaults


# Virtual aliases mappings for Postfix. This defines email forwarding
# rules in a structured format.
#
# Attention: do not forget to list handled domains in
#             run_postfix_virtual_alias_domains
#
# Dictionary structure:
#
# - Keys: criterions / pattern, usually an email address
# - Values: Lists of destinations, usually email addresses
#
# Example:
#
#   "admin@example.com":
#     - "admin@actual-destination.example.com"
#   "distribution@example.com":
#     - "user1@actual-destination.example.com"
#     - "user2@actual-destination.example.com"
#     - "user3@actual-destination.example.com"
#     - "user3@actual-destination.example.com"
#   "@example.com": # catch-all for example.com
#     - "office@example.com"
#   "@example.net": # catch-all for example.net, rewrite all to @example.com
#     - "example.com"
#
# will be ignored if run_postfix_handle_virtual is set to false.
run_postfix_virtual_alias_maps:
  {} # see __run_postfix_virtual_alias_maps_defaults in vars/main.yml for the defaults


# Switch to control whether canonical address rewriting is handled by this role.
#
# When set to true (which is the default), the role will:
#
# 1. Create and manage a config file for canonical mappings using the
#    run_postfix_canonical variable for the contents.
# 2. Set (or override) main.cf settings for the sender_canonical_maps and
#    recipient_canonical_maps options accordingly.
#
# When false, you'll need to configure these settings manually through
# run_postfix_maincf_settings or through other means.
run_postfix_handle_canonical: true


# Canonical recipient address mappings / rewrite rules for Postfix.
#
# Example:
#   "old.name@example.com": "new.name@example.com"
#   "root": "user123@example.com"
#   "@example.com": "@example.net"
#
# will be ignored if run_postfix_handle_canonical is set to false.
run_postfix_canonical_recipient:
  {} # see __run_postfix_canonical_recipient_defaults in vars/main.yml for the defaults


# Canonical sender address mappings / rewrite rules for Postfix.
#
# Examples:
#   "old.name@example.com": "new.name@example.com"
#   "root": "user123@example.com"
#   "/.+/": "do-not-reply@example.com" # rewrite all outgoing mail addresses
#   "@example.com": "@example.net"
#
# will be ignored if run_postfix_handle_canonical is set to false.
run_postfix_canonical_sender:
  {} # see __run_postfix_canonical_sender_defaults in vars/main.yml for the defaults


# Switch to control if relocated mappings settings are handled by this role.
#
# When set to true (which is the default), the role will:
#
# 1. Create and manage a config file for relocated mappings using the
#    run_postfix_relocated_maps variable for the contents.
# 2. Set (or override) main.cf settings for the relocated_maps option
#    accordingly.
#
# When false, you'll need to configure these settings manually through
# run_postfix_maincf_settings or through other means.
run_postfix_handle_relocated_maps: true


# Relocated address mapping for Postfix. It is used to tell senders that a
# recipient's address has changed. If someone tries to send email to an old
# address listed here, Postfix will generate a non-delivery report (NDR)
# with the new address ("user has moved to <new_location>" bounce messages).
#
# Dictionary structure:
#
# - Keys: criterion / pattern, usually an email address
# - Values: The new location, usually email addresses (or phone or other
#           address or location strings)
#
# Example:
#
#   "user@example.com": "new@example.net"
#   "@example.com": "Sorry, all mail has to be sent to example.net"
#
# will be ignored if run_postfix_handle_relocated_maps is set to false.
run_postfix_relocated_maps:
  {} # see __run_postfix_relocated_maps_defaults in vars/main.yml for the defaults


# Switch to control if SMTP SASL password (credentials) mappings settings are handled by this role.
#
# When set to true (which is the default), the role will:
#
# 1. Create and manage a config file for SMTP SASL password mappings using the
#    run_postfix_smtp_sasl_password_maps variable for the contents.
# 2. Set (or override) main.cf settings for the smtp_sasl_password_maps option
#    accordingly.
#
# When false, you'll need to configure these settings manually through
# run_postfix_maincf_settings or through other means.
run_postfix_handle_smtp_sasl_password_maps: true


# SMTP SASL authentication credentials for Postfix. It is used to authenticate
# Postfix when sending emails through a relay server that requires
# authentication. Each entry maps a remote SMTP server (and optionally a port)
# to a username and password.
#
# See the following documentation for more details:
# - https://www.postfix.org/SASL_README.html#client_sasl
# - https://www.postfix.org/postconf.5.html#smtp_sasl_password_maps
#
# Dictionary structure:
#
# - Keys: criterion, the destination to specify credentials for. Attention: If
#         you specify the "[" and "]" in the relayhost destination, then you
#         must use the same form here.
# - Values: The credentails, "username:password". Use
#   smtp_sasl_password_result_delimiter (default ":") to specify an alternative
#   separator between username and password.
#
# Example:
#
#   "[relay.example.com]": "user:password"
#   "[relay.example.com]:587": "johndoe:password123!"
#
# will be ignored if run_postfix_handle_smtp_sasl_password_maps is set to false.
run_postfix_smtp_sasl_password_maps:
  {} # see __run_postfix_smtp_sasl_password_maps_defaults in vars/main.yml for the defaults
