# Default variables and values for this role.
#
# These variables are designed to be easily overridden (as they have a low
# precedence) and typically allow users to customize the role's behavior.
# Each variable should have a clear comment above it, describing its purpose
# and how it fits into the role's functionality.

---

run_postfix_state: "present"

run_postfix_autoupgrade: false

run_postfix_service_state: "enabled"

run_postfix_maincf_settings:
  {} # see __run_postfix_maincf_settings_defaults in vars/main.yml for the defaults

run_postfix_mastercf_settings:
  {} # see __run_postfix_mastercf_settings_defaults in vars/main.yml for the defaults

run_postfix_relay_domains_manage: false

run_postfix_relay_domains_list_tabletype: "lmdb"

run_postfix_relay_domains_list:
  [] # see __run_postfix_relay_domains_list_defaults in vars/main.yml for the defaults

run_postfix_access_manage: false

run_postfix_access_recipient_map_tabletype: "pcre"

run_postfix_access_recipient_map:
  {} # see __run_postfix_access_recipient_map_defaults in vars/main.yml for the defaults

run_postfix_access_sender_map_tabletype: "lmdb"

run_postfix_access_sender_map:
  {} # see __run_run_postfix_access_sender_map_defaults in vars/main.yml for the defaults

run_postfix_aliases_manage: false

run_postfix_aliases_map_tabletype: "lmdb"

run_postfix_aliases_map:
  {} # see __run_postfix_aliases_map_defaults in vars/main.yml for the defaults

run_postfix_canonical_manage: false

run_postfix_canonical_recipient_map_tabletype: "lmdb"

run_postfix_canonical_recipient_map:
  {} # see __run_postfix_canonical_recipient_map_defaults in vars/main.yml for the defaults

run_postfix_canonical_sender_map_tabletype: "lmdb"

run_postfix_canonical_sender_map:
  {} # see __run_postfix_canonical_sender_map_defaults in vars/main.yml for the defaults

run_postfix_generic_manage: false

run_postfix_generic_map_tabletype: "pcre"

run_postfix_generic_map:
  {} # see __run_postfix_generic_map_defaults in vars/main.yml for the defaults

run_postfix_relocated_manage: false

run_postfix_relocated_map_tabletype: "lmdb"

run_postfix_relocated_map:
  {} # see __run_postfix_relocated_map_defaults in vars/main.yml for the defaults

run_postfix_transport_manage: false

run_postfix_transport_map_tabletype: "lmdb"

run_postfix_transport_map:
  {} # see __run_postfix_transport_map_defaults in vars/main.yml for the defaults

run_postfix_virtual_manage: false

run_postfix_virtual_aliasdomains_list_tabletype: "lmdb"

run_postfix_virtual_aliasdomains_list:
  [] # see __run_postfix_virtual_aliasdomains_list_defaults in vars/main.yml for the defaults

run_postfix_virtual_alias_map_tabletype: "lmdb"

run_postfix_virtual_alias_map:
  {} # see __run_postfix_virtual_alias_map_defaults in vars/main.yml for the defaults

run_postfix_smtp_sasl_password_manage: false

run_postfix_smtp_sasl_password_map_tabletype: "lmdb"

run_postfix_smtp_sasl_password_map:
  {} # see __run_postfix_smtp_sasl_password_map_defaults in vars/main.yml for the defaults
